print('hello world')
#print('Hi Harshal')
print("Hi harshal")
print("'Harshal'")
print('I\'m Harshal')
print('\\')
print('these /\\/\\/\\ are mountains')
print('he is\t awesome')
print('\\" \\n \\t \\\' ')
print('this is double \\\\ backslash')
print('this is \'harshal\'')
print(r'Hey, this \n \t will print as it is')
h=2
print('h')